[build-system]
requires = ["setuptools>=78.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "plumbing-3d"
version = "0.1.0"
description = "Starter package and marimo app for creating plumbing parts with CadQuery"
readme = "README.md"
requires-python = ">=3.10,<3.13"
license = { file = "LICENSE" }
dependencies = [
	"cadquery",
]

[dependency-groups]
dev = [
	"marimo",
	"plotly",
]

[tool.uv]
default-groups = ["dev"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
